dist: trusty
git:
  # use depth 2 just in case two refs get pushed at once (like a tag)
  depth: 2
language: ruby
bundler_args: --path=.bundle/gems --jobs=3 --retry=3
rvm:
- 2.6.2
- jruby-9.2.7.0
script: bundle exec rspec
