= DocBook 4.5 Converter for Asciidoctor
:idprefix:
:idseparator: -
ifdef::env-github[]
:warning-caption: :warning:
endif::[]

An Asciidoctor converter that converts AsciiDoc to DocBook 4.5.

WARNING: This converter is community maintained and will not be released.
The built-in DocBook 5 converter is preferred.

== Installation

Add the following entry to the _Gemfile_ in your project:

[,ruby]
----
gem 'asciidoctor-docbook45', github: 'asciidoctor/asciidoctor-docbook45'
----

Then, run Bundler:

 $ bundle

== Usage

When invoking the `asciidoctor` command, set the backend to `docbook45` and require this library:

 $ bundle exec asciidoctor -b docbook45 -r asciidoctor-docbook45 README.adoc

Or when using Asciidoctor via the API:

[,ruby]
----
require 'asciidoctor-docbook45'

Asciidoctor.convert_file 'README.adoc', backend: 'docbook45', safe: :safe
----

== Copyright and License

Copyright (C) 2012-2019 Dan Allen and the individual contributors to Asciidoctor.
Use of this software is granted under the terms of the MIT License.

See the link:LICENSE[] file to find the full license text.
